// GENERATED by tt_digital/gen_submission.sh from the compiler-emitted tt_um_darga_cirom.sv -- DO NOT EDIT.
// Blackbox for Darga, the CiROM digital-tier tile: the hardened
// gds/tt_um_darga_cirom.gds + lef/tt_um_darga_cirom.lef implement it. Fully digital: no analog pins.
`default_nettype none

module tt_um_darga_cirom (
    inout  wire       VGND,
    inout  wire       VDPWR,
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    // Blackbox: implemented by the hardened GDS.
endmodule
`default_nettype wire
