// GENERATED by tt_analog/gen_submission.sh from rtl/tt_analog/tt_um_azara_cirom.sv -- DO NOT EDIT.
// Blackbox for the Azara CiROM analog tile (custom_gds): the hardened
// gds/tt_um_azara_cirom.gds + lef/tt_um_azara_cirom.lef implement it. ua[0]=VREF, ua[1]=BLP, ua[2]=BLN.
`default_nettype none

module tt_um_azara_cirom (
    inout  wire       VGND,
    inout  wire       VDPWR,
    inout  wire [7:0] ua,
    input  wire [7:0] ui_in,
    output wire [7:0] uo_out,
    input  wire [7:0] uio_in,
    output wire [7:0] uio_out,
    output wire [7:0] uio_oe,
    input  wire       ena,
    input  wire       clk,
    input  wire       rst_n
);
    // Blackbox: implemented by the hardened GDS.
endmodule
`default_nettype wire
